// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OKULMVC;

#nullable disable

namespace OKULMVC.Migrations
{
    [DbContext(typeof(OkulDbcontext))]
    [Migration("20240607142825_Initdbset")]
    partial class Initdbset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OKULMVC.Models.Ders", b =>
                {
                    b.Property<int>("Dersid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dersid"));

                    b.Property<string>("Dersad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kredi")
                        .HasColumnType("int");

                    b.HasKey("Dersid");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("OKULMVC.Models.DersOgrenci", b =>
                {
                    b.Property<int>("DersOgrenciid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersOgrenciid"));

                    b.Property<int>("Dersid")
                        .HasColumnType("int");

                    b.Property<int>("Ogrenciid")
                        .HasColumnType("int");

                    b.HasKey("DersOgrenciid");

                    b.HasIndex("Dersid");

                    b.HasIndex("Ogrenciid");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("OKULMVC.Models.Ogrenci", b =>
                {
                    b.Property<int>("Ogrenciid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ogrenciid"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ogrenciid");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OKULMVC.Models.DersOgrenci", b =>
                {
                    b.HasOne("OKULMVC.Models.Ders", "Course")
                        .WithMany()
                        .HasForeignKey("Dersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OKULMVC.Models.Ogrenci", "Student")
                        .WithMany()
                        .HasForeignKey("Ogrenciid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
